name: PythonCi

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install nose
        pip install coverage
    - name: Running nosetests
      run: |
        nosetests --with-coverage --cover-erase
    - name: Analysing the code with pylint
      run: |
        pylint *
